resources:
  - name: fiscal
    type: git
    source:
      uri: https://github.com/hsiliev/strangers.git
      branch: master

jobs:
  - name: build_1
    plan:
      - get: fiscal
      - task: build
        file: scripts/ci/build.yml
      - task: test
        file: scripts/ci/test.yml
  - name: build_2
    plan:
      - get: fiscal
      - task: build
        file: scripts/ci/build.yml
      - task: test
        file: scripts/ci/test.yml